### PR TITLE
Merging -2nd try

### PR DESCRIPTION
**Pull request by zipzav**
After going over the conflicts, corrected any mistaken deletes from previous merge.

### CODE REVIEW

**Comment by scratchley** [comment]
But you reversed a lot of my changes, too. It makes me really worried and I wanted those changes that I made. 

Can you perhaps do the merge all over again from the start, or otherwise just put in your changes on top of my head revision? Aren't most of them equation related? 

I just commited more changes and that should be all for the next while (pardon the summary and description for the commit with summary ".gitignore" -- that summary and description was not intentional). Perhaps let me know when you are doing your work and I'll make sure not to do changes at that time. 

Please confirm receipt of this email. 

Thanks, 
Craig

**Comment by zipzav** [comment]
Hi Craig!

I realised you said you added things is morning? Looking at your
repository, there's no commit from you this morning or am I mistaken? Maybe
the commits aren't pushed yet? If that is the case, I can wait for that
commit and then re-do the merge.

When you said I reverted some of your changes did you mean from changes
from the morning?
I was comparing your repository before any of my commits to the version
attached will my 2nd pull request:

https://github.com/scratchley/ensc180_textbook_scratchley/compare/5975bba189e8eb1124a1a1f73aee26ab39264c8d...zipzav:master
(Does this link for you?)

and I'm trying to find which of your revisions I've reverted?


-Zavier

**Comment by zipzav** [comment]
Oh! Do you mean your commit: "Merge pull request #1 from zipzav/master"?
I was confused and though this just means you pulled my commits, am I mistaken? Does the above commit include your most recent changes?

**Comment by scratchley** [comment]
Yes, let me check this. Can you give me permission to push to your account? 

Craig

**Comment by zipzav** [comment]
I've gone ahead and invited you to be a collaborator.
Link to invitation: https://github.com/zipzav/ensc180_textbook/invitations

**Pull request closed without merging**
